/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.109
 * Generated at: 2025-10-05 14:08:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import ipl.TeamDaoImp;
import ipl.Team;

public final class addTeam_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("ipl.Team");
    _jspx_imports_classes.add("ipl.TeamDaoImp");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <title>Add New Team – IPL Admin</title>\r\n");
      out.write("  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <style>\r\n");
      out.write("    body {\r\n");
      out.write("      background: url('2.jpg') no-repeat center center fixed; /* Please ensure '2.jpg' is the correct path for your image */\r\n");
      out.write("      background-size: cover;\r\n");
      out.write("      margin: 0;\r\n");
      out.write("      padding: 0;\r\n");
      out.write("      backdrop-filter: blur(4px);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-container {\r\n");
      out.write("      max-width: 600px;\r\n");
      out.write("      margin: 60px auto;\r\n");
      out.write("      background: rgba(255, 255, 255, 0.1);\r\n");
      out.write("      backdrop-filter: blur(10px);\r\n");
      out.write("      border-radius: 15px;\r\n");
      out.write("      padding: 40px;\r\n");
      out.write("      box-shadow: 0 8px 30px rgba(0, 0, 0, 0.3);\r\n");
      out.write("      color: #fff;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-title {\r\n");
      out.write("      margin-bottom: 25px;\r\n");
      out.write("      text-align: center;\r\n");
      out.write("      color: #ffc107;\r\n");
      out.write("      font-size: 28px;\r\n");
      out.write("      font-weight: bold;\r\n");
      out.write("      text-shadow: 1px 1px 2px #000;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    label {\r\n");
      out.write("      font-weight: 500;\r\n");
      out.write("      color: #fff;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-control {\r\n");
      out.write("      background-color: rgba(255, 255, 255, 0.15);\r\n");
      out.write("      border: 1px solid rgba(255, 255, 255, 0.3);\r\n");
      out.write("      color: #fff;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-control::placeholder {\r\n");
      out.write("      color: #eee;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-control:focus {\r\n");
      out.write("      background-color: rgba(255, 255, 255, 0.25);\r\n");
      out.write("      color: #fff;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .input-group-text {\r\n");
      out.write("      background-color: rgba(255, 255, 255, 0.2);\r\n");
      out.write("      border: none;\r\n");
      out.write("      color: #fff;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .alert {\r\n");
      out.write("      font-size: 15px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn-success {\r\n");
      out.write("      background-color: #28a745;\r\n");
      out.write("      border: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn-success:hover {\r\n");
      out.write("      background-color: #218838;\r\n");
      out.write("    }\r\n");
      out.write("        .back-link {\r\n");
      out.write("      position: absolute;\r\n");
      out.write("      top: 15px;\r\n");
      out.write("      left: 20px;\r\n");
      out.write("      color: #ccc;\r\n");
      out.write("      font-size: 20px;\r\n");
      out.write("      text-decoration: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .back-link:hover {\r\n");
      out.write("      color: purple;\r\n");
      out.write("    }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<a href=\"admindash.jsp\" class=\"back-link\"><i class=\"fas fa-arrow-left\"></i> Back</a>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("  <div class=\"form-container\">\r\n");
      out.write("    <h2 class=\"form-title\"><i class=\"fas fa-plus-circle\"></i> Add New IPL Team</h2>\r\n");
      out.write("\r\n");
      out.write("    ");
 
      // Retrieve status and potentially the duplicate team code from the URL
      String status = request.getParameter("status");
      String teamCodeParam = request.getParameter("teamCode");
      
      // ONLY display error/duplicate messages
      if ("error".equals(status)) {
    
      out.write("\r\n");
      out.write("      <div class=\"alert alert-danger text-center\">❌ Failed to add team. Please check the data and try again.</div>\r\n");
      out.write("    ");
 
      } else if ("duplicate".equals(status)) {
    
      out.write("\r\n");
      out.write("      <div class=\"alert alert-warning text-center\">⚠️ Already exists! Please Check  the details .</div>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <form action=\"TeamServlet?action=add\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("      \r\n");
      out.write("      <!-- Team Code (Removed persistence) -->\r\n");
      out.write("      <div class=\"mb-3 input-group\">\r\n");
      out.write("        <span class=\"input-group-text\"><i class=\"fas fa-code\"></i></span>\r\n");
      out.write("        <input type=\"text\" class=\"form-control\" name=\"teamCode\" placeholder=\"Team Code (e.g., MI, RCB)\" maxlength=\"3\" required>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Team Name (Removed persistence) -->\r\n");
      out.write("      <div class=\"mb-3 input-group\">\r\n");
      out.write("        <span class=\"input-group-text\"><i class=\"fas fa-shield-alt\"></i></span>\r\n");
      out.write("        <input type=\"text\" class=\"form-control\" name=\"teamName\" placeholder=\"Team Name\" required>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Country (readonly) -->\r\n");
      out.write("      <div class=\"mb-3 input-group\">\r\n");
      out.write("        <span class=\"input-group-text\"><i class=\"fas fa-flag\"></i></span>\r\n");
      out.write("        <input type=\"text\" class=\"form-control\" name=\"country\" value=\"India\" readonly>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Coach Name (Removed persistence) -->\r\n");
      out.write("      <div class=\"mb-3 input-group\">\r\n");
      out.write("        <span class=\"input-group-text\"><i class=\"fas fa-chalkboard-teacher\"></i></span>\r\n");
      out.write("        <input type=\"text\" class=\"form-control\" name=\"coachName\" placeholder=\"Coach Name\" required>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Captain Name (Removed persistence) -->\r\n");
      out.write("      <div class=\"mb-3 input-group\">\r\n");
      out.write("        <span class=\"input-group-text\"><i class=\"fas fa-user-tie\"></i></span>\r\n");
      out.write("        <input type=\"text\" class=\"form-control\" name=\"captainName\" placeholder=\"Captain Name\" required>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Team Logo -->\r\n");
      out.write("      <div class=\"mb-3\">\r\n");
      out.write("        <label class=\"form-label\"><i class=\"fas fa-image\"></i> Team Logo</label>\r\n");
      out.write("        <input type=\"file\" class=\"form-control\" name=\"teamLogo\" accept=\"image/*\" required>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"d-grid\">\r\n");
      out.write("        <button type=\"submit\" class=\"btn btn-success\"><i class=\"fas fa-check-circle\"></i> Add Team</button>\r\n");
      out.write("      </div>\r\n");
      out.write("    </form>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap JS -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
