/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.109
 * Generated at: 2025-10-13 12:16:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <title>🏏-IPL Management</title>\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css\">\r\n");
      out.write("  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  \r\n");
      out.write("  <style>\r\n");
      out.write("    :root {\r\n");
      out.write("      --bg-dark: #1a1a1a;\r\n");
      out.write("      --card-dark: #242424;\r\n");
      out.write("      --accent-orange: #ff6600;\r\n");
      out.write("      --accent-blue: #00aaff;\r\n");
      out.write("      --text-light: #f5f5f5;\r\n");
      out.write("      --text-muted: #bbbbbb;\r\n");
      out.write("      --shadow-blue: 0 4px 15px rgba(0, 174, 255, 0.2);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    body {\r\n");
      out.write("      background-color: var(--bg-dark);\r\n");
      out.write("      color: var(--text-light);\r\n");
      out.write("      font-family: 'Poppins', sans-serif;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Navbar */\r\n");
      out.write("    .navbar {\r\n");
      out.write("      background-color: var(--card-dark);\r\n");
      out.write("      padding: 10px;\r\n");
      out.write("      border-bottom: 1px solid #333;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .navbar .container-fluid {\r\n");
      out.write("      display: flex;\r\n");
      out.write("      justify-content: center;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("      gap: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .navbar-brand {\r\n");
      out.write("      font-weight: bold;\r\n");
      out.write("      font-size: 1.8rem;\r\n");
      out.write("      color: white;\r\n");
      out.write("      font-family: 'Brush Script MT';\r\n");
      out.write("      display: flex;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("      gap: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .navbar-brand img {\r\n");
      out.write("      width: 80px;\r\n");
      out.write("      height: auto;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn-admin {\r\n");
      out.write("      position: absolute;\r\n");
      out.write("      right: 20px;\r\n");
      out.write("      top: 10px;\r\n");
      out.write("      background-color: var(--accent-orange);\r\n");
      out.write("      color: white;\r\n");
      out.write("      padding: 6px 15px;\r\n");
      out.write("      border-radius: 4px;\r\n");
      out.write("      font-weight: 600;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .nav-link {\r\n");
      out.write("      color: white !important;\r\n");
      out.write("    } \r\n");
      out.write("    .navbar-brand:hover,\r\n");
      out.write("    .navbar-brand:focus {\r\n");
      out.write("      color: white !important; \r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .nav-link:hover,\r\n");
      out.write("    .nav-link:focus {\r\n");
      out.write("      color: var(--accent-blue) !important;\r\n");
      out.write("      background: transparent !important;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Carousel */\r\n");
      out.write("    .hero-carousel {\r\n");
      out.write("      height: 500px;\r\n");
      out.write("      overflow: hidden;\r\n");
      out.write("      position: relative;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .hero-carousel .carousel-inner,\r\n");
      out.write("    .hero-carousel .carousel-item {\r\n");
      out.write("      height: 100%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .hero-bg {\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      height: 100%;\r\n");
      out.write("      object-fit: cover;\r\n");
      out.write("      filter: grayscale(10%) brightness(0.55);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .hero-content {\r\n");
      out.write("      position: absolute;\r\n");
      out.write("      top: 50%;\r\n");
      out.write("      left: 10%;\r\n");
      out.write("      transform: translateY(-50%);\r\n");
      out.write("      z-index: 2;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .hero-content h1 {\r\n");
      out.write("      font-size: 3.5rem;\r\n");
      out.write("      font-weight: bold;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .hero-content p {\r\n");
      out.write("      font-size: 1.2rem;\r\n");
      out.write("      color: var(--text-muted);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .section-title {\r\n");
      out.write("      font-size: 2rem;\r\n");
      out.write("      font-weight: 700;\r\n");
      out.write("      color: white;\r\n");
      out.write("      margin: 50px 0 10px;\r\n");
      out.write("      text-align: center;\r\n");
      out.write("      position: relative;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .section-title::after {\r\n");
      out.write("      content: '';\r\n");
      out.write("      display: block;\r\n");
      out.write("      width: 150px;\r\n");
      out.write("      height: 3px;\r\n");
      out.write("      background-color: #28a745;\r\n");
      out.write("      margin: 10px auto 0;\r\n");
      out.write("      border-radius: 2px;\r\n");
      out.write("    }\r\n");
      out.write("    .card:hover {\r\n");
      out.write("      transform: translateY(-8px);\r\n");
      out.write("      box-shadow: 0 0 30px rgba(0, 195, 255, 0.3);\r\n");
      out.write("    }\r\n");
      out.write("    .card-custom {\r\n");
      out.write("      background-color: var(--card-dark);\r\n");
      out.write("      border-radius: 15px;\r\n");
      out.write("      box-shadow: var(--shadow-blue);\r\n");
      out.write("      transition: all 0.3s;\r\n");
      out.write("      height: 100%;\r\n");
      out.write("      display: flex;\r\n");
      out.write("      flex-direction: column;\r\n");
      out.write("      justify-content: space-between;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .card-custom .card-img-top {\r\n");
      out.write("      height: 200px;\r\n");
      out.write("      object-fit: cover;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .card-custom .card-title {\r\n");
      out.write("      color: #28a745;\r\n");
      out.write("      font-weight: bold;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .card-custom .card-text {\r\n");
      out.write("      color: white;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .points-card {\r\n");
      out.write("      background-color: var(--card-dark);\r\n");
      out.write("      border-radius: 15px;\r\n");
      out.write("      padding: 20px;\r\n");
      out.write("      box-shadow: var(--shadow-blue);\r\n");
      out.write("      margin-bottom: 20px;\r\n");
      out.write("      text-align: center;\r\n");
      out.write("      color: var(--text-light);\r\n");
      out.write("      transition: all 0.3s ;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .points-card img {\r\n");
      out.write("      width: 80px;\r\n");
      out.write("      margin: 10px 0;\r\n");
      out.write("    }\r\n");
      out.write("    .points-card:hover {\r\n");
      out.write("      transform: translateY(-8px);\r\n");
      out.write("      box-shadow: 0 0 30px rgba(0, 195, 255, 0.3);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-circle span {\r\n");
      out.write("      background: #333;\r\n");
      out.write("      padding: 5px 12px;\r\n");
      out.write("      border-radius: 50%;\r\n");
      out.write("      margin: 2px;\r\n");
      out.write("      font-weight: bold;\r\n");
      out.write("      display: inline-block;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-circle span.win {\r\n");
      out.write("      background: green;\r\n");
      out.write("      color: white;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-circle span.loss {\r\n");
      out.write("      background: red;\r\n");
      out.write("      color: white;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .top-player {\r\n");
      out.write("      text-align: center;\r\n");
      out.write("      padding: 40px;\r\n");
      out.write("      background-color: #111;\r\n");
      out.write("      border-radius: 15px;\r\n");
      out.write("      margin-top: 30px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .top-player img {\r\n");
      out.write("      width: 180px;\r\n");
      out.write("      border-radius: 10px;\r\n");
      out.write("      box-shadow: 0 0 20px rgba(0, 174, 255, 0.4);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .about-box {\r\n");
      out.write("      background-color: #1f1f1f;\r\n");
      out.write("      box-shadow: 0 0 25px rgba(255, 255, 255, 0.08);\r\n");
      out.write("      border-radius: 20px;\r\n");
      out.write("      padding: 40px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("/* Dock Style - Modern IPL Edition */\r\n");
      out.write(".dock-container {\r\n");
      out.write("  position: fixed;\r\n");
      out.write("  bottom: 30px;\r\n");
      out.write("  left: 50%;\r\n");
      out.write("  transform: translateX(-50%);\r\n");
      out.write("  background: rgba(0, 0, 0, 0.6);\r\n");
      out.write("  backdrop-filter: blur(12px);\r\n");
      out.write("  padding: 14px 28px;\r\n");
      out.write("  border-radius: 30px;\r\n");
      out.write("  display: flex;\r\n");
      out.write("  align-items: center;\r\n");
      out.write("  box-shadow: 0 10px 30px rgba(0, 174, 255, 0.2);\r\n");
      out.write("  z-index: 9999;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dock-item {\r\n");
      out.write("  margin: 0 12px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  transition: all 0.3s ease;\r\n");
      out.write("  position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dock-item a {\r\n");
      out.write("  display: flex;\r\n");
      out.write("  flex-direction: column;\r\n");
      out.write("  align-items: center;\r\n");
      out.write("  font-size: 13px;\r\n");
      out.write("  color: var(--text-muted);\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  transition: color 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dock-item i {\r\n");
      out.write("  font-size: 22px;\r\n");
      out.write("  margin-bottom: 3px;\r\n");
      out.write("  transition: transform 0.3s ease, color 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dock-item:hover i {\r\n");
      out.write("  transform: translateY(-6px) scale(1.2);\r\n");
      out.write("  color: var(--accent-orange);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dock-item a:hover {\r\n");
      out.write("  color: var(--accent-orange);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Active item style */\r\n");
      out.write(".dock-item a.active i,\r\n");
      out.write(".dock-item a.active {\r\n");
      out.write("  color: var(--accent-orange);\r\n");
      out.write("  font-weight: bold;\r\n");
      out.write("  text-shadow: 0 0 10px rgba(255, 102, 0, 0.6);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("footer {\r\n");
      out.write("  background-color: var(--card-dark);\r\n");
      out.write("  padding: 25px;\r\n");
      out.write("  color: var(--text-muted);\r\n");
      out.write("      margin-top: 120px;\r\n");
      out.write("      text-align: left;\r\n");
      out.write("    }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  <nav class=\"navbar navbar-expand-lg\">\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("      <a class=\"navbar-brand\" href=\"main.jsp\">\r\n");
      out.write("        <img src=\"https://documents.iplt20.com/ipl/assets/images/ipl-logo-new-old.png\" alt=\"IPL Logo\"> IPL Management\r\n");
      out.write("      </a>\r\n");
      out.write("      <a href=\"adlogin.jsp\" class=\"btn btn-admin ms-auto\">Admin Login</a>\r\n");
      out.write("    </div>\r\n");
      out.write("  </nav>\r\n");
      out.write("\r\n");
      out.write("  <div id=\"heroCarousel\" class=\"carousel slide hero-carousel\" data-bs-ride=\"carousel\">\r\n");
      out.write("    <div class=\"carousel-inner\">\r\n");
      out.write("      <div class=\"carousel-item active\"><img src=\"1.jpg\" class=\"hero-bg\" alt=\"...\"></div>\r\n");
      out.write("      <div class=\"carousel-item\"><img src=\"2.jpg\" class=\"hero-bg\" alt=\"...\"></div>\r\n");
      out.write("      <div class=\"carousel-item\"><img src=\"96.jpg\" class=\"hero-bg\" alt=\"...\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"hero-content\">\r\n");
      out.write("      <h1>MS DHONI💞</h1>\r\n");
      out.write("      <p>“You Don’t play for the crowd, You are playing for the country.”</p>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <h2 class=\"section-title\">Most Iconic IPL Moments</h2>\r\n");
      out.write("    <div class=\"row row-cols-1 row-cols-md-4 g-4\">\r\n");
      out.write("      <div class=\"col\">\r\n");
      out.write("        <div class=\"card card-custom h-100\">\r\n");
      out.write("          <img src=\"RCB-Win-IPL-upl.jpg\" class=\"card-img-top\" alt=\"RCB Win\">\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("            <h5 class=\"card-title\">RCB Won the Cup</h5>\r\n");
      out.write("            <p class=\"card-text\">RCB won their maiden title in IPL 2025, defeating Punjab Kings.</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col\">\r\n");
      out.write("        <div class=\"card card-custom h-100\">\r\n");
      out.write("          <img src=\"csk.jpeg\" class=\"card-img-top\" alt=\"CSK Table Bottom\">\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("            <h5 class=\"card-title\">CSK At Table Bottom</h5>\r\n");
      out.write("            <p class=\"card-text\">For the first time in IPL history, CSK ended the season at the bottom.</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col\">\r\n");
      out.write("        <div class=\"card card-custom h-100\">\r\n");
      out.write("          <img src=\"vai.jpeg\" class=\"card-img-top\" alt=\"Vaibhav Suryavanshi\">\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("            <h5 class=\"card-title\">Vaibhav Suryavanshi</h5>\r\n");
      out.write("            <p class=\"card-text\">14-year-old Vaibhav scored a century in 38 balls – youngest ever!</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col\">\r\n");
      out.write("        <div class=\"card card-custom h-100\">\r\n");
      out.write("          <img src=\"che.jpeg\" class=\"card-img-top\" alt=\"Chepauk Roar\">\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("            <h5 class=\"card-title\">Chepauk Roar</h5>\r\n");
      out.write("            <p class=\"card-text\">RCB defeated CSK at Chepauk after 17 years. Massive noise!</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"container mt-5 about-box\">\r\n");
      out.write("    <h2 class=\"section-title\">About IPL Foundation</h2>\r\n");
      out.write("    <div class=\"row align-items-center\">\r\n");
      out.write("      <div class=\"col-md-6\">\r\n");
      out.write("        <p>The Indian Premier League (IPL) was launched in 2007 and began in April 2008. Teams like CSK, MI, RCB, and KKR created a global tournament.</p>\r\n");
      out.write("        <p>The IPL is now not just a cricket league — it’s an emotion that unites millions across the world.</p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-md-6 text-center\">\r\n");
      out.write("        <img src=\"ipl.jpeg\" width=\"400\" class=\"rounded img-fluid\" alt=\"IPL Trophy\">\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"container mt-5\">\r\n");
      out.write("    <h2 class=\"section-title\">Points Table</h2>\r\n");
      out.write("    <div class=\"row row-cols-1 row-cols-md-3 g-4\">\r\n");
      out.write("      <div class=\"col\">\r\n");
      out.write("        <div class=\"points-card\">\r\n");
      out.write("          <h3>1. Punjab Kings</h3>\r\n");
      out.write("          <img src=\"https://www.iplt20.com/teams/PBKS.png\" alt=\"PBKS Logo\">\r\n");
      out.write("          <p><strong>Points:</strong> 19 | <strong>Played:</strong> 14 | <strong>Won:</strong> 9 | <strong>NRR:</strong> 0.372</p>\r\n");
      out.write("          <div class=\"form-circle\"><span class=\"win\">W</span><span class=\"loss\">L</span><span class=\"win\">W</span><span class=\"win\">W</span></div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col\">\r\n");
      out.write("        <div class=\"points-card\">\r\n");
      out.write("          <h3>2. RCB</h3>\r\n");
      out.write("          <img src=\"https://www.iplt20.com/teams/RCB.png\" alt=\"RCB Logo\">\r\n");
      out.write("          <p><strong>Points:</strong> 19 | <strong>Played:</strong> 14 | <strong>Won:</strong> 9 | <strong>NRR:</strong> 0.301</p>\r\n");
      out.write("          <div class=\"form-circle\"><span class=\"loss\">L</span><span class=\"win\">W</span><span class=\"win\">W</span></div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col\">\r\n");
      out.write("        <div class=\"points-card\">\r\n");
      out.write("          <h3>3. Gujarat Titans</h3>\r\n");
      out.write("          <img src=\"https://www.iplt20.com/teams/GT.png\" alt=\"GT Logo\">\r\n");
      out.write("          <p><strong>Points:</strong> 18 | <strong>Played:</strong> 14 | <strong>Won:</strong> 9 | <strong>NRR:</strong> 0.294</p>\r\n");
      out.write("          <div class=\"form-circle\"><span class=\"loss\">L</span><span class=\"loss\">L</span><span class=\"win\">W</span></div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"container mt-5\">\r\n");
      out.write("    <h2 class=\"section-title\">Top Performer - Orange Cap</h2>\r\n");
      out.write("    <div class=\"top-player\">\r\n");
      out.write("      <img src=\"sai.png\" alt=\"Sai Sudharsan\">\r\n");
      out.write("      <h2>Sai Sudharsan</h2>\r\n");
      out.write("      <p>🏏 759 Runs in IPL 2025</p>\r\n");
      out.write("      <p><strong>M:</strong> 15 | <strong>HS:</strong> 108* | <strong>Avg:</strong> 54.21 | <strong>4/6s:</strong> 88/21 | <strong>100s/50s:</strong> 6/11</p>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"dock-container\">\r\n");
      out.write(" <div class=\"dock-item\"><a href=\"main.jsp\" title=\"Home\"><i class=\"fa-solid fa-house\"></i> Home</a></div>\r\n");
      out.write("    <div class=\"dock-item\"><a href=\"teams.jsp\" title=\"Teams\"><i class=\"fa-solid fa-users\"></i> Teams</a></div>\r\n");
      out.write("  <div class=\"dock-item\"><a href=\"players.jsp\"  title=\"Players\"><i class=\"fa-solid fa-user\"></i> Players</a></div>\r\n");
      out.write("  <div class=\"dock-item\"><a href=\"Matches.jsp\" title=\"Matches\"><i class=\"fa-solid fa-chart-line\"></i> Matches</a></div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <footer>\r\n");
      out.write("    <p>© 2025 IPL Management System. All Rights Reserved.</p>\r\n");
      out.write("  </footer>\r\n");
      out.write("\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
