/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.109
 * Generated at: 2025-10-05 06:50:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import ipl.Team;
import ipl.TeamDaoImp;

public final class teams_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("ipl.Team");
    _jspx_imports_classes.add("ipl.TeamDaoImp");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <title>IPL Management-Teams</title>\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css\">\r\n");
      out.write("\r\n");
      out.write("  <style>\r\n");
      out.write("    :root {\r\n");
      out.write("      --bg-dark: #1a1a1a;\r\n");
      out.write("      --card-dark: #242424;\r\n");
      out.write("      --text-light: #f5f5f5;\r\n");
      out.write("      --accent-orange: #ff6600;\r\n");
      out.write("      --shadow-blue: 0 4px 15px rgba(0, 174, 255, 0.2);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    body {\r\n");
      out.write("      background-color: var(--bg-dark);\r\n");
      out.write("      color: var(--text-light);\r\n");
      out.write("      font-family: 'Poppins', sans-serif;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Navbar */\r\n");
      out.write("    .navbar {\r\n");
      out.write("      background-color: var(--card-dark);\r\n");
      out.write("      padding: 10px;\r\n");
      out.write("      border-bottom: 1px solid #333;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .navbar .container-fluid {\r\n");
      out.write("      display: flex;\r\n");
      out.write("      justify-content: center;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("      gap: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .navbar-brand {\r\n");
      out.write("      font-weight: bold;\r\n");
      out.write("      font-size: 1.8rem;\r\n");
      out.write("      color: white;\r\n");
      out.write("      font-family: 'Brush Script MT';\r\n");
      out.write("      display: flex;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("      gap: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .navbar-brand img {\r\n");
      out.write("      width: 80px;\r\n");
      out.write("      height: auto;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn-admin {\r\n");
      out.write("      position: absolute;\r\n");
      out.write("      right: 20px;\r\n");
      out.write("      top: 10px;\r\n");
      out.write("      background-color: var(--accent-orange);\r\n");
      out.write("      color: white;\r\n");
      out.write("      padding: 6px 15px;\r\n");
      out.write("      border-radius: 4px;\r\n");
      out.write("      font-weight: 600;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .nav-link {\r\n");
      out.write("      color: white !important;\r\n");
      out.write("    } \r\n");
      out.write("    .navbar-brand:hover,\r\n");
      out.write("    .navbar-brand:focus {\r\n");
      out.write("      color: white !important; \r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .nav-link:hover,\r\n");
      out.write("    .nav-link:focus {\r\n");
      out.write("      color: var(--accent-blue) !important;\r\n");
      out.write("      background: transparent !important;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Dock style */\r\n");
      out.write("    .dock-container {\r\n");
      out.write("      display: flex;\r\n");
      out.write("      justify-content: center;\r\n");
      out.write("      gap: 30px;\r\n");
      out.write("      margin: 20px 0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .dock-item {\r\n");
      out.write("      transition: transform 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .dock-item:hover {\r\n");
      out.write("      transform: scale(1.3) translateY(-10px);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .dock-item a {\r\n");
      out.write("      color: var(--text-light);\r\n");
      out.write("      text-decoration: none;\r\n");
      out.write("      font-size: 1.1rem;\r\n");
      out.write("      font-weight: 500;\r\n");
      out.write("      padding: 8px 15px;\r\n");
      out.write("      border-radius: 8px;\r\n");
      out.write("      background-color: #333;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .dock-item a.active,\r\n");
      out.write("    .dock-item a:hover {\r\n");
      out.write("      background-color: var(--accent-orange);\r\n");
      out.write("      color: #fff;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write(".section-title {\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  font-size: 28px;\r\n");
      out.write("  font-weight: 600;\r\n");
      out.write("  margin-top: 30px;\r\n");
      out.write("  margin-bottom: 10px;\r\n");
      out.write("  position: relative;\r\n");
      out.write("  color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".section-title::after {\r\n");
      out.write("  content: \"\";\r\n");
      out.write("  display: block;\r\n");
      out.write("  width: 130px;\r\n");
      out.write("  height: 3px;\r\n");
      out.write("  background-color: red;\r\n");
      out.write("  margin: 10px auto 0 auto;\r\n");
      out.write("  border-radius: 4px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search-bar {\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  margin: 15px auto;\r\n");
      out.write("}\r\n");
      out.write(".search-bar input {\r\n");
      out.write("  width: 50%;\r\n");
      out.write("  padding: 10px;\r\n");
      out.write("  border-radius: 6px;\r\n");
      out.write("  background-color: #333;\r\n");
      out.write("  color: white;\r\n");
      out.write("  border: 1px solid #555;\r\n");
      out.write("  font-size: 14px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".team-card {\r\n");
      out.write("  background-color: #1e1e1e;\r\n");
      out.write("  border-radius: 15px;\r\n");
      out.write("  overflow: hidden;\r\n");
      out.write("  box-shadow: 0 0 20px rgba(0, 195, 255, 0.2);\r\n");
      out.write("  transition: transform 0.3s ease, box-shadow 0.3s ease;\r\n");
      out.write("  display: flex;\r\n");
      out.write("  flex-direction: column;\r\n");
      out.write("  height: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".team-card:hover {\r\n");
      out.write("  transform: translateY(-8px);\r\n");
      out.write("  box-shadow: 0 0 30px rgba(0, 195, 255, 0.3);\r\n");
      out.write("}\r\n");
      out.write(".image-wrapper {\r\n");
      out.write("  position: relative;\r\n");
      out.write("  height: 250px; /* was 300px */\r\n");
      out.write("  overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".image-wrapper img {\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  height: 100%;\r\n");
      out.write("  object-fit: cover;\r\n");
      out.write("  display: block;\r\n");
      out.write("  transition: transform 0.4s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".image-wrapper:hover img {\r\n");
      out.write("  transform: scale(1.05);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".overlay {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  top: 0;\r\n");
      out.write("  left: 0;\r\n");
      out.write("  height: 100%;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  background-color: rgba(0, 0, 0, 0.01);\r\n");
      out.write("  backdrop-filter: blur(3px);\r\n");
      out.write("  opacity: 0;\r\n");
      out.write("  transition: opacity 0.4s ease;\r\n");
      out.write("  display: flex;\r\n");
      out.write("  align-items: center;\r\n");
      out.write("  justify-content: center;\r\n");
      out.write("  padding: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".image-wrapper:hover .overlay {\r\n");
      out.write("  opacity: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".overlay-content {\r\n");
      out.write("  color: #ffffff;\r\n");
      out.write("  font-size: 16px;\r\n");
      out.write("  font-weight: bold;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  line-height: 1.8;\r\n");
      out.write("  background-color: rgba(0, 0, 0, 0.25);\r\n");
      out.write("  padding: 15px;\r\n");
      out.write("  border-radius: 8px;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".overlay-content p {\r\n");
      out.write("  margin: 6px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".overlay-content p strong {\r\n");
      out.write("  color: #00e6e6;\r\n");
      out.write("  font-weight: 700;\r\n");
      out.write("  margin-right: 8px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-footer {\r\n");
      out.write("  padding: 20px;\r\n");
      out.write("  margin-top: auto;\r\n");
      out.write("  background-color: #151515;\r\n");
      out.write("  display: flex;\r\n");
      out.write("  justify-content: space-between;\r\n");
      out.write("  align-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".team-name {\r\n");
      out.write("  font-size: 18px;\r\n");
      out.write("  font-weight: 700;\r\n");
      out.write("  color: #28a745;\r\n");
      out.write("  margin: 0;\r\n");
      out.write("  line-height: 1.3;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".team-name:hover {\r\n");
      out.write("  font-weight: bold;\r\n");
      out.write("  transform: scale(1.05);\r\n");
      out.write("  color: #00ffff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("footer {\r\n");
      out.write("  background-color: var(--card-dark);\r\n");
      out.write("  padding: 10px;\r\n");
      out.write("  color: #6d6969;\r\n");
      out.write("  margin-top: 120px;\r\n");
      out.write("  text-align: left;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  <!-- Navbar -->\r\n");
      out.write("  <nav class=\"navbar navbar-expand-lg\">\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("      <a class=\"navbar-brand\" href=\"#\">\r\n");
      out.write("        <img src=\"https://documents.iplt20.com/ipl/assets/images/ipl-logo-new-old.png\" alt=\"IPL Logo\"> IPL Management\r\n");
      out.write("      </a>\r\n");
      out.write("    </div>\r\n");
      out.write("  </nav>\r\n");
      out.write("\r\n");
      out.write("  <!-- Dock-like Nav -->\r\n");
      out.write("  <div class=\"dock-container\">\r\n");
      out.write("  <div class=\"dock-item\"><a href=\"main.jsp\" title=\"Home\"><i class=\"fa-solid fa-house\"></i> Home</a></div>\r\n");
      out.write("    <div class=\"dock-item\"><a href=\"#\" class=\"active\"><i class=\"fas fa-users\"></i> Teams</a></div>\r\n");
      out.write("    <div class=\"dock-item\"><a href=\"players.jsp\"><i class=\"fas fa-user\"></i> Players</a></div>\r\n");
      out.write("    <div class=\"dock-item\"><a href=\"#\"><i class=\"fas fa-chart-line\"></i> Matches</a></div>\r\n");
      out.write("    <!-- <div class=\"dock-item\"><a href=\"#\"><i class=\"fas fa-cog\"></i> Settings</a></div> -->\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!-- Section Title -->\r\n");
      out.write("  <div class=\"section-title\">Teams:</div>\r\n");
      out.write("  <!-- Search Bar -->\r\n");
      out.write("<div class=\"search-bar\">\r\n");
      out.write("  <input type=\"text\" id=\"searchInput\" placeholder=\"Search teams by names...\" onkeyup=\"filterTeams()\">\r\n");
      out.write("</div>\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("  <!-- Cards Grid -->\r\n");
      out.write("  <div class=\"container mt-3\">\r\n");
      out.write("<div class=\"row row-cols-1 row-cols-md-3 g-4 align-items-stretch\">\r\n");
      out.write("      ");

        TeamDaoImp dao = new TeamDaoImp();
        List<Team> teams = dao.getAllTeams();
        for (Team t : teams) {
      
      out.write("\r\n");
      out.write("<div class=\"col\">\r\n");
      out.write("  <div class=\"team-card\">\r\n");
      out.write("    <div class=\"image-wrapper\">\r\n");
      out.write("      <img src=\"");
      out.print( t.getLogoPath() );
      out.write("\" alt=\"Team Logo\">\r\n");
      out.write("      <div class=\"overlay\">\r\n");
      out.write("        <div class=\"overlay-content\">\r\n");
      out.write("          <p><strong>Coach:</strong> ");
      out.print( t.getCoachName() );
      out.write("</p>\r\n");
      out.write("          <p><strong>Captain:</strong> ");
      out.print( t.getCaptainName() );
      out.write("</p>\r\n");
      out.write("          <p><strong>Country:</strong> ");
      out.print( t.getCountry() );
      out.write("</p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"card-footer\">\r\n");
      out.write("      <h5 class=\"team-name\">");
      out.print( t.getTeamName() );
      out.write(' ');
      out.write('(');
      out.print( t.getTeamCode() );
      out.write(")</h5>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("      ");

        }
      
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <footer>\r\n");
      out.write("    <p>© 2025 IPL Management System. All Rights Reserved.</p>\r\n");
      out.write("  </footer>\r\n");
      out.write("\r\n");
      out.write("  <!-- Scripts -->\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("  <script>\r\n");
      out.write("    function filterTeams() {\r\n");
      out.write("      var input = document.getElementById(\"searchInput\").value.toLowerCase();\r\n");
      out.write("      var cards = document.getElementsByClassName(\"team-card\");\r\n");
      out.write("      for (var i = 0; i < cards.length; i++) {\r\n");
      out.write("        var cardText = cards[i].innerText.toLowerCase();\r\n");
      out.write("        cards[i].parentElement.style.display = cardText.includes(input) ? \"\" : \"none\";\r\n");
      out.write("      }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  </script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
